Repository algorand/pyteal, pull requests merged in 2022-01, with the labels that each got.

#166 Print diff of `__init__.pyi`
  pyteal/__init__.pyi
  scripts/generate_init.py
Labels: Unplanned, Team Scytale

#163 Add BytesSqrt
  pyteal/__init__.pyi
  pyteal/ast/__init__.py
  pyteal/ast/unaryexpr.py
  pyteal/ast/unaryexpr_test.py
  pyteal/ir/ops.py
Labels: external contribution, Team Scytale

#165 Acct params get
  pyteal/__init__.pyi
  pyteal/ast/__init__.py
  pyteal/ast/acct.py
  pyteal/ast/acct_test.py
  pyteal/ir/ops.py
Labels: Team Scytale
